### ISSUE TITLE
Equivalent summary statistics for network benchmark

### ISSUE THREAD

**Issue by spresman** [ekernf01/ggrn#1]
Hi Eric,
The regression benchmark works great! I'm still having some trouble (a new issue now) with the outputs of my network perturbation benchmark. Grouping the data by networks yields equivalent metric values across all the networks. I sent you all relevant files to your email. Thanks a lot!

**Comment by ekernf01** [comment]
Great! I see you are using the 'regulon' backend, and I think I found the bug there. It's in ggrn, so I will transfer this issue and I will push the fix shortly.

**Comment by ekernf01** [comment]
Fix pushed, and github auto-closes when I do that, but I need to mention a couple things:

- You will need to update `ggrn`, not `pereggrn`, to get this fix.
- I see your experiment uses every perturbation in the test data. This is definitely one type of fair comparison, but there are other options that could also be considered fair and are more generous towards certain networks. I say this because not every network contains all of the regulators perturbed in the Nakatake data. You might be interested in running an experiment where the test set contains only the regulators present in every network. You can do this by adding to the metadata:

`"allowed_regulators_vs_network_regulators": "intersection", `

Sorry that this is not documented in the reference.

**Comment by ekernf01** [comment]
Also: you need to delete the predictions (`outputs/predictions/*.h5ad`) or pass `--amount_to_do models` when calling `pereggrn`. The evaluation code was fine, and the problem was that the predictions were all identical and wrong. So the predictions need to be deleted. By default, `pereggrn` will not overwrite them because the default for `--amount_to_do` is `missing_models`.
